#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# shellcheck disable=SC1090
source "$DIR/../lib/sh"

chk::linux || exit 0

# ensure development tools are installed
sudo apt-get -qq update && sudo apt-get -qq install \
  --no-install-recommends \
  build-essential \
  curl \
  libbz2-dev \
  libffi-dev \
  liblzma-dev \
  libncurses5-dev \
  libreadline-dev \
  libsqlite3-dev \
  libssl-dev \
  libxml2-dev \
  libxmlsec1-dev \
  llvm \
  make \
  tk-dev \
  wget \
  xz-utils \
  zlib1g-dev

rm -rf ~/Videos/
rm -rf ~/Music/
rm -rf ~/Documents/
rm -rf ~/Downloads/
rm -rf ~/Pictures/
rm -rf ~/Public/
rm -rf ~/Templates/
