#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# shellcheck disable=SC1090
source "$DIR/../lib/sh"

if chk::osx
then
  ln -s /usr/bin/pip3 ~/bin/pip
  ln -s /usr/bin/python3 ~/bin/python

  grep -qF -- "export PATH=$HOME/bin:$PATH" ~/.bashrc || echo "export PATH=$HOME/bin:$PATH" >> ~/.bashrc
  source $HOME/.bashrc
fi

if chk::linux
then
  sudo ln -s /home/linuxbrew/.linuxbrew/bin/pip3 /usr/bin/pip
  sudo ln -s /home/linuxbrew/.linuxbrew/bin/python3 /usr/bin/python
fi
