#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# shellcheck disable=SC1090
source "$DIR/../lib/sh"

# many asdf plugins rely on jq
pkg::install::asdf jq https://github.com/russelltsherman/asdf-jq.git

pkg::install::asdf adr-tools https://github.com/russelltsherman/asdf-adr-tools.git
pkg::install::asdf draft https://github.com/kristoflemmens/asdf-draft.git
pkg::install::asdf eksctl https://github.com/russelltsherman/asdf-eksctl.git
pkg::install::asdf fzf https://github.com/russelltsherman/asdf-fzf.git
pkg::install::asdf gcloud https://github.com/jthegedus/asdf-gcloud.git
pkg::install::asdf github-cli https://github.com/russelltsherman/asdf-github-cli.git
pkg::install::asdf golang https://github.com/kennyp/asdf-golang.git
pkg::install::asdf goreleaser https://github.com/kforsthoevel/asdf-goreleaser.git
pkg::install::asdf helm https://github.com/Antiarchitect/asdf-helm.git
pkg::install::asdf hugo https://bitbucket.org/mgladdish/asdf-gohugo.git
pkg::install::asdf istioctl https://github.com/rafik8/asdf-istioctl.git
pkg::install::asdf java https://github.com/halcyon/asdf-java
pkg::install::asdf jmespath https://github.com/skyzyx/asdf-jmespath
pkg::install::asdf k9s https://github.com/looztra/asdf-k9s
pkg::install::asdf kubectl https://github.com/Banno/asdf-kubectl.git
pkg::install::asdf maven https://github.com/halcyon/asdf-maven.git
pkg::install::asdf minikube https://github.com/russelltsherman/asdf-minikube.git
pkg::install::asdf neovim https://github.com/richin13/asdf-neovim.git

asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
bash -c '${ASDF_DATA_DIR}/plugins/nodejs/bin/import-release-team-keyring'
bash -c '${ASDF_DATA_DIR}/plugins/nodejs/bin/import-previous-release-team-keyring'
asdf install "nodejs" "$(asdf list-all "nodejs" | grep -v a | grep -v e | grep -v c | grep -v y | tail -1 | xargs)"
asdf global "nodejs" "$(asdf list "nodejs" | tail -1 | xargs)"

pkg::install::asdf operator-sdk https://github.com/Medium/asdf-operator-sdk
pkg::install::asdf packer https://github.com/Banno/asdf-hashicorp.git
# pkg::install::asdf popeye https://github.com/nlamirault/asdf-popeye.git
pkg::install::asdf python https://github.com/danhper/asdf-python.git
pkg::install::asdf ruby https://github.com/asdf-vm/asdf-ruby.git
# pkg::install::asdf skaffold https://github.com/kristoflemmens/asdf-skaffold.git
pkg::install::asdf sqlite https://github.com/cLupus/asdf-sqlite.git
# pkg::install::asdf stern https://github.com/russelltsherman/asdf-stern
pkg::install::asdf terraform https://github.com/Banno/asdf-hashicorp.git
pkg::install::asdf terragrunt https://github.com/lotia/asdf-terragrunt.git
# pkg::install::asdf tilt https://github.com/eaceaser/asdf-tilt.git
pkg::install::asdf tmux https://github.com/aphecetche/asdf-tmux.git
pkg::install::asdf vendir https://github.com/k14s/asdf-k14s.git
# pkg::install::asdf waypoint https://github.com/Banno/asdf-hashicorp.git
pkg::install::asdf yarn https://github.com/twuni/asdf-yarn.git
