#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# shellcheck disable=SC1090
source "$DIR/../lib/sh"

ASDF_DIR="$(xdg_dir "asdf")"
export ASDF_DIR
# shellcheck disable=SC1090
source "$ASDF_DIR/asdf.sh"

pkg::install::asdf direnv https://github.com/russelltsherman/asdf-direnv

mkdir -p ${XDG_CONFIG_HOME}/direnv

cat > ${XDG_CONFIG_HOME}/direnv/direnvrc <<- EOM
# makes the use asdf feature available
source "\$(asdf direnv hook asdf)"

# Uncomment the following line to make direnv silent by default.
# export DIRENV_LOG_FORMAT=""
EOM
