#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# shellcheck disable=SC1090
source "$DIR/../lib/sh"

chk::linux && sudo sudo apt-get -qq update && sudo sudo apt-get -qq install -y curl hdparm pv unzip

wget https://github.com/hypriot/flash/releases/download/2.7.0/flash -O ~/bin/flash
chmod +x ~/bin/flash
