#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# shellcheck disable=SC1090
source "$DIR/../lib/sh"

KPOOF_DIR="$(xdg_dir "kpoof")"
export KPOOF_DIR

git clone https://github.com/farmotive/kpoof "$KPOOF_DIR"
ln -s "$KPOOF_DIR/kpoof" ~/bin/kpoof
