#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# shellcheck disable=SC1090
source "$DIR/../lib/sh"

# i don't care for this installing into $HOME
# i would prefer sending it to XDG_CONFIG_HOME
# export KREW_DIR="$(xdg_dir "krew")"

wget "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz"
tar -zxvf krew.tar.gz

KREW=./krew-"$(uname | tr '[:upper:]' '[:lower:]')_$(uname -m | sed -e 's/x86_64/amd64/' -e 's/arm.*$/arm/')"
"$KREW" install krew
rm -rf krew*

kubectl krew install ctx # kubectl ctx
kubectl krew install ns # kubectl ns

# look for more useful plugins
# https://krew.sigs.k8s.io/plugins/
