#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# shellcheck disable=SC1090
source "$DIR/../lib/sh"

chk::osx && pkg::install::brew 'coreutils'
chk::osx && pkg::install::brew 'gpg'

chk::linux && pkg::install::debian 'curl dirmngr gpg'

asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git

bash -c '${ASDF_DATA_DIR}/plugins/nodejs/bin/import-release-team-keyring'
bash -c '${ASDF_DATA_DIR}/plugins/nodejs/bin/import-previous-release-team-keyring'

asdf install "nodejs" "$(asdf list-all "nodejs" | grep -v a | grep -v e | grep -v c | grep -v y | tail -1 | xargs)"

asdf global "nodejs" "$(asdf list "nodejs" | tail -1 | xargs)"
