#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# shellcheck disable=SC1090
source "$DIR/../lib/sh"

chk::osx && pkg::install::brew 'coreutils'
chk::osx && pkg::install::brew 'gpg'

chk::debian && pkg::install::debian 'curl dirmngr gpg'

bash -c '${ASDF_DATA_DIR}/plugins/nodejs/bin/import-release-team-keyring'
bash -c '${ASDF_DATA_DIR}/plugins/nodejs/bin/import-previous-release-team-keyring'

pkg::install::asdf nodejs https://github.com/asdf-vm/asdf-nodejs.git
