#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# shellcheck disable=SC1090
source "$DIR/../lib/sh"

if chk::osx
then
  pkg::install::brew "python3"
  sudo ln -s /usr/bin/pip3 /usr/bin/pip
  sudo ln -s /usr/bin/python3 /usr/bin/python
fi

if chk::ubuntu || chk::debian
then
  sudo apt-get update
  sudo apt-get install -y \
    python3 \
    python3-pip

  sudo ln -s /usr/bin/pip3 /usr/bin/pip
  sudo ln -s /usr/bin/python3 /usr/bin/python
fi
